version: "3.9"

services:
   bot:
    build: .
    container_name: bot_app
    env_file:
      - .env
    volumes:
      - ${TARGET_FOLDER}:${TARGET_FOLDER}:ro
      - bot_data:/app/tmp
    command: >
      sh -c "alembic upgrade head && python main.py"
    restart: unless-stopped
volumes:
  bot_data:
  
